# server config
server:
  # run mode ： dev debug product
  run_mode: dev
  # http port
  http_port: 8082
  # read time out /S
  read_timeout: 60
  # write time out /S
  write_timeout: 60
#etcd:
#  endpoint:
#    - "http://127.0.0.1:2379"
#  dial_timeout: 5
kubernetes:
  kubeconfig: './denovo.yaml'
logging:
  level: debug
  json: false
# Casbin权限策略配置
casbin_path:
  model_path: './config/file/rbac_model.conf'