// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/denovo/permission/config"
	"github.com/denovo/permission/pkg/casbin"
	"github.com/denovo/permission/pkg/kubenates"
	"github.com/denovo/permission/pkg/signal"
	"github.com/denovo/permission/pkg/store"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.OpsLinkConfig) (*OpsLinkServer, error) {
	casbin, err := initCasbin(cfg)
	if err != nil {
		return nil, err
	}
	storeService, err := initStore(cfg)
	if err != nil {
		return nil, err
	}
	k8sClient, err := initOpsKube(cfg)
	if err != nil {
		return nil, err
	}
	signalService, err := initSignalService(cfg)
	if err != nil {
		return nil, err
	}
	opsLinkServer, err := NewOpsLinkServer(cfg, casbin, storeService, k8sClient, signalService)
	if err != nil {
		return nil, err
	}
	return opsLinkServer, nil
}

// wire.go:

func initCasbin(conf *config.OpsLinkConfig) (*casbin.Casbin, error) {
	return casbin.InitCasbin(conf)
}

func initStore(conf *config.OpsLinkConfig) (store.StoreService, error) {
	return store.NewStoreService(conf)
}

func initSignalService(conf *config.OpsLinkConfig) (*signal.SignalService, error) {
	return signal.NewSignalService(), nil
}

func initOpsKube(conf *config.OpsLinkConfig) (*kubenates.K8sClient, error) {
	return kubenates.NewK8sConfig(conf)
}
