// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package pkg

import (
	"github.com/denovo/permission/configration"
	"github.com/denovo/permission/pkg/casbin"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.OpsLinkConfig) (*OpsLinkServer, error) {
	casbin, err := initCasbin(cfg)
	if err != nil {
		return nil, err
	}

	opsLinkServer, err := NewOpsLinkServer(cfg, casbin)
	if err != nil {
		return nil, err
	}
	return opsLinkServer, nil
}

// wire.go:

func initCasbin(conf *config.OpsLinkConfig) (*casbin.Casbin, error) {
	return casbin.InitCasbin(conf)
}
