// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: ops_policy.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PType     string `protobuf:"bytes,1,opt,name=p_type,json=pType,proto3" json:"p_type,omitempty"`
	UserRole  string `protobuf:"bytes,2,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Source    string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Action    string `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *PModel) Reset() {
	*x = PModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ops_policy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PModel) ProtoMessage() {}

func (x *PModel) ProtoReflect() protoreflect.Message {
	mi := &file_ops_policy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PModel.ProtoReflect.Descriptor instead.
func (*PModel) Descriptor() ([]byte, []int) {
	return file_ops_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PModel) GetPType() string {
	if x != nil {
		return x.PType
	}
	return ""
}

func (x *PModel) GetUserRole() string {
	if x != nil {
		return x.UserRole
	}
	return ""
}

func (x *PModel) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PModel) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PModel) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type GModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PType string `protobuf:"bytes,1,opt,name=p_type,json=pType,proto3" json:"p_type,omitempty"`
	User  string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Role  string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *GModel) Reset() {
	*x = GModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ops_policy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GModel) ProtoMessage() {}

func (x *GModel) ProtoReflect() protoreflect.Message {
	mi := &file_ops_policy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GModel.ProtoReflect.Descriptor instead.
func (*GModel) Descriptor() ([]byte, []int) {
	return file_ops_policy_proto_rawDescGZIP(), []int{1}
}

func (x *GModel) GetPType() string {
	if x != nil {
		return x.PType
	}
	return ""
}

func (x *GModel) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *GModel) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldPolicy *PModel `protobuf:"bytes,1,opt,name=old_policy,json=oldPolicy,proto3" json:"old_policy,omitempty"`
	NewPolicy *PModel `protobuf:"bytes,2,opt,name=new_policy,json=newPolicy,proto3" json:"new_policy,omitempty"`
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ops_policy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_policy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_ops_policy_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetOldPolicy() *PModel {
	if x != nil {
		return x.OldPolicy
	}
	return nil
}

func (x *UpdateRequest) GetNewPolicy() *PModel {
	if x != nil {
		return x.NewPolicy
	}
	return nil
}

type BackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PPolicy []*PModel `protobuf:"bytes,1,rep,name=p_policy,json=pPolicy,proto3" json:"p_policy,omitempty"`
	GPolicy []*GModel `protobuf:"bytes,2,rep,name=g_policy,json=gPolicy,proto3" json:"g_policy,omitempty"`
}

func (x *BackResp) Reset() {
	*x = BackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ops_policy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackResp) ProtoMessage() {}

func (x *BackResp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_policy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackResp.ProtoReflect.Descriptor instead.
func (*BackResp) Descriptor() ([]byte, []int) {
	return file_ops_policy_proto_rawDescGZIP(), []int{3}
}

func (x *BackResp) GetPPolicy() []*PModel {
	if x != nil {
		return x.PPolicy
	}
	return nil
}

func (x *BackResp) GetGPolicy() []*GModel {
	if x != nil {
		return x.GPolicy
	}
	return nil
}

var File_ops_policy_proto protoreflect.FileDescriptor

var file_ops_policy_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6f, 0x70, 0x73, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x06, 0x70, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x47, 0x0a, 0x06, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x15, 0x0a, 0x06, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x69,
	0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2b, 0x0a, 0x0a, 0x6f, 0x6c, 0x64, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x52, 0x09, 0x6f, 0x6c, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x2b, 0x0a, 0x0a,
	0x6e, 0x65, 0x77, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x09,
	0x6e, 0x65, 0x77, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x5c, 0x0a, 0x08, 0x42, 0x61, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x08, 0x70, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x07, 0x70, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x27,
	0x0a, 0x08, 0x67, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x07,
	0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ops_policy_proto_rawDescOnce sync.Once
	file_ops_policy_proto_rawDescData = file_ops_policy_proto_rawDesc
)

func file_ops_policy_proto_rawDescGZIP() []byte {
	file_ops_policy_proto_rawDescOnce.Do(func() {
		file_ops_policy_proto_rawDescData = protoimpl.X.CompressGZIP(file_ops_policy_proto_rawDescData)
	})
	return file_ops_policy_proto_rawDescData
}

var file_ops_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ops_policy_proto_goTypes = []interface{}{
	(*PModel)(nil),        // 0: role.pModel
	(*GModel)(nil),        // 1: role.gModel
	(*UpdateRequest)(nil), // 2: role.UpdateRequest
	(*BackResp)(nil),      // 3: role.BackResp
}
var file_ops_policy_proto_depIdxs = []int32{
	0, // 0: role.UpdateRequest.old_policy:type_name -> role.pModel
	0, // 1: role.UpdateRequest.new_policy:type_name -> role.pModel
	0, // 2: role.BackResp.p_policy:type_name -> role.pModel
	1, // 3: role.BackResp.g_policy:type_name -> role.gModel
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ops_policy_proto_init() }
func file_ops_policy_proto_init() {
	if File_ops_policy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ops_policy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ops_policy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ops_policy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ops_policy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ops_policy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ops_policy_proto_goTypes,
		DependencyIndexes: file_ops_policy_proto_depIdxs,
		MessageInfos:      file_ops_policy_proto_msgTypes,
	}.Build()
	File_ops_policy_proto = out.File
	file_ops_policy_proto_rawDesc = nil
	file_ops_policy_proto_goTypes = nil
	file_ops_policy_proto_depIdxs = nil
}
